export default [
  {
    id: 1,
    fullWord: 'DRAGON',
    puzzle: 'D _ A _ O N',
    hint: 'Mythical fire creature',
  },
  {
    id: 2,
    fullWord: 'TEMPLE',
    puzzle: 'T _ M _ L E',
    hint: 'Sacred spiritual place',
  },
  {
    id: 3,
    fullWord: 'LEGEND',
    puzzle: 'L _ G E _ D',
    hint: 'Ancient mythical story',
  },
  {
    id: 4,
    fullWord: 'MYTHOLOGY',
    puzzle: 'M Y _ H _ L O G Y',
    hint: 'Collection of ancient stories',
  },
  {
    id: 5,
    fullWord: 'PHOENIX',
    puzzle: 'P _ O E _ I X',
    hint: 'Bird reborn from fire',
  },
  {
    id: 6,
    fullWord: 'CASTLE',
    puzzle: 'C _ S T _ E',
    hint: 'Medieval stone fortress',
  },
  {
    id: 7,
    fullWord: 'EMPEROR',
    puzzle: 'E M _ E R _ R',
    hint: 'Ancient royal ruler',
  },
  {
    id: 8,
    fullWord: 'SHRINE',
    puzzle: 'S _ R I _ E',
    hint: 'Sacred place of worship',
  },
  {
    id: 9,
    fullWord: 'VOLCANO',
    puzzle: 'V O _ C A _ O',
    hint: 'Mountain with lava',
  },
  {
    id: 10,
    fullWord: 'MONUMENT',
    puzzle: 'M O _ U M E _ T',
    hint: 'Historic public structure',
  },
  {
    id: 11,
    fullWord: 'THUNDER',
    puzzle: 'T H _ N D _ R',
    hint: 'Loud storm sound',
  },
  {
    id: 12,
    fullWord: 'WARRIOR',
    puzzle: 'W _ R R I _ R',
    hint: 'Ancient skilled fighter',
  },
  {
    id: 13,
    fullWord: 'TREASURE',
    puzzle: 'T R _ A S _ R E',
    hint: 'Valuable hidden riches',
  },
  {
    id: 14,
    fullWord: 'DYNASTY',
    puzzle: 'D Y _ A S T _',
    hint: 'Long royal family rule',
  },
  {
    id: 15,
    fullWord: 'KINGDOM',
    puzzle: 'K I _ G D _ M',
    hint: 'Land ruled by a king',
  },
  {
    id: 16,
    fullWord: 'FIREBALL',
    puzzle: 'F I _ E B _ L L',
    hint: 'Explosive sphere of flame',
  },
  {
    id: 17,
    fullWord: 'GUARDIAN',
    puzzle: 'G U _ R D I _ N',
    hint: 'Mythical protector',
  },
  {
    id: 18,
    fullWord: 'CAVERN',
    puzzle: 'C _ V E _ N',
    hint: 'Large underground cave',
  },
  {
    id: 19,
    fullWord: 'RELIC',
    puzzle: 'R _ L I C',
    hint: 'Ancient sacred object',
  },
  {
    id: 20,
    fullWord: 'SORCERER',
    puzzle: 'S O _ C E _ E R',
    hint: 'Powerful magic user',
  },
  {
    id: 21,
    fullWord: 'PROPHECY',
    puzzle: 'P R O _ H E _ Y',
    hint: 'Prediction of the future',
  },
  {
    id: 22,
    fullWord: 'COMPASS',
    puzzle: 'C O _ P A _ S',
    hint: 'Tool used for navigation',
  },
  {
    id: 23,
    fullWord: 'SPIRIT',
    puzzle: 'S _ I R I T',
    hint: 'Supernatural being',
  },
  {
    id: 24,
    fullWord: 'MYSTERY',
    puzzle: 'M Y _ T E _ Y',
    hint: 'Something unexplained',
  },
  {
    id: 25,
    fullWord: 'ANCIENT',
    puzzle: 'A N _ I E _ T',
    hint: 'Very old civilization',
  },
  {
    id: 26,
    fullWord: 'DRAGONSCALE',
    puzzle: 'D R A _ O N S _ A L E',
    hint: 'Armor-like dragon skin',
  },
  {
    id: 27,
    fullWord: 'LABYRINTH',
    puzzle: 'L A _ Y R I _ T H',
    hint: 'Complex maze structure',
  },
  {
    id: 28,
    fullWord: 'CELESTIAL',
    puzzle: 'C E _ E S T I _ L',
    hint: 'Connected to the heavens',
  },
  {
    id: 29,
    fullWord: 'RITUAL',
    puzzle: 'R I _ U A L',
    hint: 'Sacred ceremonial act',
  },
  {
    id: 30,
    fullWord: 'SKYFIRE',
    puzzle: 'S K _ F I _ E',
    hint: 'Flame falling from above',
  },
];