export default [
  {
    id: 1,
    question: 'Which country is known as the Land of the Thunder Dragon?',
    options: [
      { key: 'A', text: 'China' },
      { key: 'B', text: 'Japan' },
      { key: 'C', text: 'Bhutan' },
      { key: 'D', text: 'Korea' },
    ],
    correct: 'C',
  },
  {
    id: 2,
    question: 'Which creature symbolizes wisdom in Asian mythology?',
    options: [
      { key: 'A', text: 'Wolf' },
      { key: 'B', text: 'Dragon' },
      { key: 'C', text: 'Tiger' },
      { key: 'D', text: 'Raven' },
    ],
    correct: 'B',
  },
  {
    id: 3,
    question: 'What element are dragons commonly connected to?',
    options: [
      { key: 'A', text: 'Fire' },
      { key: 'B', text: 'Sand' },
      { key: 'C', text: 'Steel' },
      { key: 'D', text: 'Ice' },
    ],
    correct: 'A',
  },
  {
    id: 4,
    question: 'Which city is famous for Dragon Bridge?',
    options: [
      { key: 'A', text: 'Tokyo' },
      { key: 'B', text: 'Da Nang' },
      { key: 'C', text: 'Bangkok' },
      { key: 'D', text: 'Seoul' },
    ],
    correct: 'B',
  },
  {
    id: 5,
    question: 'What do dragons often guard in legends?',
    options: [
      { key: 'A', text: 'Ships' },
      { key: 'B', text: 'Forests' },
      { key: 'C', text: 'Treasure' },
      { key: 'D', text: 'Rivers' },
    ],
    correct: 'C',
  },
  {
    id: 6,
    question: 'Which continent has Drakensberg Mountains?',
    options: [
      { key: 'A', text: 'Europe' },
      { key: 'B', text: 'Asia' },
      { key: 'C', text: 'Africa' },
      { key: 'D', text: 'Australia' },
    ],
    correct: 'C',
  },
  {
    id: 7,
    question: 'What color are Chinese imperial dragons often shown as?',
    options: [
      { key: 'A', text: 'Green' },
      { key: 'B', text: 'Black' },
      { key: 'C', text: 'White' },
      { key: 'D', text: 'Gold' },
    ],
    correct: 'D',
  },
  {
    id: 8,
    question: 'Which animal became a dragon in ancient legend?',
    options: [
      { key: 'A', text: 'Snake' },
      { key: 'B', text: 'Carp' },
      { key: 'C', text: 'Eagle' },
      { key: 'D', text: 'Fox' },
    ],
    correct: 'B',
  },
  {
    id: 9,
    question: 'What do Japanese water dragons control?',
    options: [
      { key: 'A', text: 'Sandstorms' },
      { key: 'B', text: 'Volcanoes' },
      { key: 'C', text: 'Rivers' },
      { key: 'D', text: 'Forests' },
    ],
    correct: 'C',
  },
  {
    id: 10,
    question: 'Which temple features a giant pink dragon?',
    options: [
      { key: 'A', text: 'Longshan' },
      { key: 'B', text: 'Wat Samphran' },
      { key: 'C', text: 'Ryujin' },
      { key: 'D', text: 'Lung Mo' },
    ],
    correct: 'B',
  },
  {
    id: 11,
    question: 'Dragons in Europe were often seen as?',
    options: [
      { key: 'A', text: 'Protectors' },
      { key: 'B', text: 'Gods' },
      { key: 'C', text: 'Monsters' },
      { key: 'D', text: 'Spirits' },
    ],
    correct: 'C',
  },
  {
    id: 12,
    question: 'Which country is famous for dragon festivals?',
    options: [
      { key: 'A', text: 'Japan' },
      { key: 'B', text: 'Egypt' },
      { key: 'C', text: 'Brazil' },
      { key: 'D', text: 'Canada' },
    ],
    correct: 'A',
  },
  {
    id: 13,
    question: 'What do dragons symbolize in China?',
    options: [
      { key: 'A', text: 'Chaos' },
      { key: 'B', text: 'Luck' },
      { key: 'C', text: 'Fear' },
      { key: 'D', text: 'Winter' },
    ],
    correct: 'B',
  },
  {
    id: 14,
    question: 'Which natural place is called Dragon Mountains?',
    options: [
      { key: 'A', text: 'Alps' },
      { key: 'B', text: 'Himalayas' },
      { key: 'C', text: 'Andes' },
      { key: 'D', text: 'Drakensberg' },
    ],
    correct: 'D',
  },
  {
    id: 15,
    question: 'Which creature breathes fire in legends?',
    options: [
      { key: 'A', text: 'Griffin' },
      { key: 'B', text: 'Phoenix' },
      { key: 'C', text: 'Dragon' },
      { key: 'D', text: 'Kraken' },
    ],
    correct: 'C',
  },
  {
    id: 16,
    question: 'What do monks use in dragon rituals?',
    options: [
      { key: 'A', text: 'Lanterns' },
      { key: 'B', text: 'Coins' },
      { key: 'C', text: 'Spears' },
      { key: 'D', text: 'Crowns' },
    ],
    correct: 'A',
  },
  {
    id: 17,
    question: 'Which dragon type is connected to oceans?',
    options: [
      { key: 'A', text: 'Fire Dragon' },
      { key: 'B', text: 'Sea Dragon' },
      { key: 'C', text: 'Shadow Dragon' },
      { key: 'D', text: 'Stone Dragon' },
    ],
    correct: 'B',
  },
  {
    id: 18,
    question: 'Which city contains many dragon shrines?',
    options: [
      { key: 'A', text: 'Kyoto' },
      { key: 'B', text: 'Dubai' },
      { key: 'C', text: 'Madrid' },
      { key: 'D', text: 'Oslo' },
    ],
    correct: 'A',
  },
  {
    id: 19,
    question: 'Dragons are commonly shown with?',
    options: [
      { key: 'A', text: 'Wings' },
      { key: 'B', text: 'Horns' },
      { key: 'C', text: 'Claws' },
      { key: 'D', text: 'All of these' },
    ],
    correct: 'D',
  },
  {
    id: 20,
    question: 'Which culture worshipped celestial dragons?',
    options: [
      { key: 'A', text: 'Viking' },
      { key: 'B', text: 'Chinese' },
      { key: 'C', text: 'Roman' },
      { key: 'D', text: 'Persian' },
    ],
    correct: 'B',
  },
  {
    id: 21,
    question: 'What protects ancient dragon temples?',
    options: [
      { key: 'A', text: 'Statues' },
      { key: 'B', text: 'Knights' },
      { key: 'C', text: 'Bridges' },
      { key: 'D', text: 'Ships' },
    ],
    correct: 'A',
  },
  {
    id: 22,
    question: 'Which dragon is linked to storms?',
    options: [
      { key: 'A', text: 'Sky Dragon' },
      { key: 'B', text: 'Forest Dragon' },
      { key: 'C', text: 'Cave Dragon' },
      { key: 'D', text: 'Desert Dragon' },
    ],
    correct: 'A',
  },
  {
    id: 23,
    question: 'Dragons often appear in?',
    options: [
      { key: 'A', text: 'Mythology' },
      { key: 'B', text: 'Chemistry' },
      { key: 'C', text: 'Politics' },
      { key: 'D', text: 'Sports' },
    ],
    correct: 'A',
  },
  {
    id: 24,
    question: 'Which material are dragon statues often carved from?',
    options: [
      { key: 'A', text: 'Stone' },
      { key: 'B', text: 'Plastic' },
      { key: 'C', text: 'Glass' },
      { key: 'D', text: 'Paper' },
    ],
    correct: 'A',
  },
  {
    id: 25,
    question: 'What glows in many dragon legends?',
    options: [
      { key: 'A', text: 'Eyes' },
      { key: 'B', text: 'Armor' },
      { key: 'C', text: 'Trees' },
      { key: 'D', text: 'Rivers' },
    ],
    correct: 'A',
  },
  {
    id: 26,
    question: 'What do dragons symbolize in Japan?',
    options: [
      { key: 'A', text: 'Wisdom' },
      { key: 'B', text: 'Hunger' },
      { key: 'C', text: 'Fear' },
      { key: 'D', text: 'Silence' },
    ],
    correct: 'A',
  },
  {
    id: 27,
    question: 'Which place is linked to hidden dragon tunnels?',
    options: [
      { key: 'A', text: 'Kyoto' },
      { key: 'B', text: 'Venice' },
      { key: 'C', text: 'Paris' },
      { key: 'D', text: 'Cairo' },
    ],
    correct: 'A',
  },
  {
    id: 28,
    question: 'What do dragons usually guard in temples?',
    options: [
      { key: 'A', text: 'Relics' },
      { key: 'B', text: 'Food' },
      { key: 'C', text: 'Weapons' },
      { key: 'D', text: 'Animals' },
    ],
    correct: 'A',
  },
  {
    id: 29,
    question: 'Which dragon is connected to volcanoes?',
    options: [
      { key: 'A', text: 'Crimson Dragon' },
      { key: 'B', text: 'Ice Dragon' },
      { key: 'C', text: 'River Dragon' },
      { key: 'D', text: 'Wind Dragon' },
    ],
    correct: 'A',
  },
  {
    id: 30,
    question: 'What is the main theme of dragon mythology?',
    options: [
      { key: 'A', text: 'Technology' },
      { key: 'B', text: 'Power' },
      { key: 'C', text: 'Fashion' },
      { key: 'D', text: 'Racing' },
    ],
    correct: 'B',
  },
];